CarGallery/Models/Fabricante.cs
using System.ComponentModel.DataAnnotations;

namespace CarGallery.Models
{
    public class Fabricante
    {
        public int Id { get; set; }
        
        [Required(ErrorMessage = "Campo nome é obrigatório")]
        public String Nome { get; set; }

        [Required(ErrorMessage = "Campo descrição é obrigatório")]
        public String Descricao { get; set; }

        public List<Carro> Carros { get; set; } = new List<Carro>(); 
    }
}

CarGallery/Controllers/CarroController.cs
using CarGallery.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.IO;
using System.Linq;

namespace CarGallery.Controllers
{
    [Authorize]
    public class CarroController : Controller
    {
        private readonly CarGalleryContext _context;

        public CarroController(CarGalleryContext context)
        {
            _context = context;
        }

        // Action para exibir o formulário de criação de um novo carro
        public IActionResult Create()
        {
            var fabricantes = _context.Fabricantes.ToList();
            ViewBag.fabricantes = fabricantes;
            return View();
        }

        // Action para processar o formulário de criação de um novo carro
        [HttpPost]
        public IActionResult Create([FromForm] Carro carro, [Bind("idFabricante")] int idFabricante)
        {
            var fabricante = _context.Fabricantes.FirstOrDefault(x => x.Id == idFabricante);
            if (fabricante == null)
                throw new Exception("Fabricante não encontrado");

            var image = Request.Form.Files.GetFile("imageFile");

            if (image != null && !image.ContentType.StartsWith("image/"))
            {
                ModelState.AddModelError("image_error", "Extensão de arquivo não permitida");

                var fabricantes = _context.Fabricantes.ToList();
                ViewBag.fabricantes = fabricantes;

                return View();
            }

            var fileName = image.FileName;
            var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "imagens_carros", image.FileName);

            using (Stream stream = new FileStream(path, FileMode.Create))
            {
                image.CopyTo(stream);
                stream.Flush();
            }

            carro.Imagem = $"/imagens_carros/{image.FileName}";
            fabricante.Carros.Add(carro);

            _context.Fabricantes.Update(fabricante);
            _context.SaveChanges();

            return RedirectToAction("Index", "Fabricante");
        }

        // Action para exibir os detalhes de um carro específico
        [AllowAnonymous] // Permite que usuários não autenticados acessem esta action
        [HttpGet("/Carro/Detail/{id}")] // Define a rota personalizada para a action Detail
        public IActionResult Detail(int id)
        {
            var carro = _context.Carros.Find(id);
            if (carro == null)
            {
                return NotFound();
            }

            return View(carro);
        }
    }
}

CarGallery/Controllers/FabricanteController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using CarGallery;
using CarGallery.Models;
using Microsoft.AspNetCore.Authorization;

namespace CarGallery.Controllers
{
    [Authorize]
    public class FabricanteController : Controller
    {
        private readonly CarGalleryContext _context;

        public FabricanteController(CarGalleryContext context)
        {
            _context = context;
        }

        // GET: Fabricante
        public async Task<IActionResult> Index()
        {
            return View(await _context.Fabricantes.ToListAsync());
        }

        // GET: Fabricante/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var fabricante = await _context.Fabricantes
                .FirstOrDefaultAsync(m => m.Id == id);
            if (fabricante == null)
            {
                return NotFound();
            }

            return View(fabricante);
        }

        // GET: Fabricante/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Fabricante/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nome,Descricao")] Fabricante fabricante)
        {
            if (ModelState.IsValid)
            {
                _context.Add(fabricante);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(fabricante);
        }

        // GET: Fabricante/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var fabricante = await _context.Fabricantes.FindAsync(id);
            if (fabricante == null)
            {
                return NotFound();
            }
            return View(fabricante);
        }

        // POST: Fabricante/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nome,Descricao")] Fabricante fabricante)
        {
            if (id != fabricante.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(fabricante);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FabricanteExists(fabricante.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(fabricante);
        }

        // GET: Fabricante/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var fabricante = await _context.Fabricantes
                .FirstOrDefaultAsync(m => m.Id == id);
            if (fabricante == null)
            {
                return NotFound();
            }

            return View(fabricante);
        }

        // POST: Fabricante/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var fabricante = await _context.Fabricantes.FindAsync(id);
            if (fabricante != null)
            {
                // Exclui todos os carros associados ao fabricante
                var carros = await _context.Carros
                    .Where(c => c.FabricanteId == id)
                    .ToListAsync();
                _context.Carros.RemoveRange(carros);

                _context.Fabricantes.Remove(fabricante);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool FabricanteExists(int id)
        {
            return _context.Fabricantes.Any(e => e.Id == id);
        }
    }
}

CarGallery/Views/Fabricante/Create.cshtml
@model CarGallery.Models.Fabricante

@{
    ViewData["Title"] = "Create";
}

<h1>Create Fabricante</h1>

<div class="row">
    <div class="col-md-6">
        <form asp-action="Create" class="needs-validation" novalidate>
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="mb-3">
                <label asp-for="Nome" class="form-label">Nome</label>
                <input asp-for="Nome" class="form-control" required>
                <div class="invalid-feedback">Por favor, insira um nome.</div>
            </div>
            <div class="mb-3">
                <label asp-for="Descricao" class="form-label">Descrição</label>
                <input asp-for="Descricao" class="form-control">
                <div class="invalid-feedback">Por favor, insira uma descrição.</div>
            </div>
            <hr class="mb-4">
            <button class="btn btn-primary btn-lg btn-block" type="submit">Criar</button>
        </form>
    </div>
</div>

<div class="mt-3">
    <a asp-action="Index" class="btn btn-secondary">Voltar à Lista</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

CarGallery/Views/Fabricante/Delete.cshtml
@model CarGallery.Models.Fabricante

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Fabricante</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Descricao)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Descricao)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

CarGallery/Views/Fabricante/Details.cshtml
@model CarGallery.Models.Fabricante

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Fabricante</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Descricao)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Descricao)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

CarGallery/Views/Fabricante/Edit.cshtml
@model CarGallery.Models.Fabricante

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Fabricante</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Descricao" class="control-label"></label>
                <input asp-for="Descricao" class="form-control" />
                <span asp-validation-for="Descricao" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CarGallery/Views/Fabricante/Index.cshtml
@model IEnumerable<CarGallery.Models.Fabricante>

@{
    ViewData["Title"] = "Fabricantes";
}

<h1 class="text-center">Fabricantes</h1>

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <p>
                <a href="@Url.Action("Create")" class="btn btn-primary">Criar novo fabricante</a>
                <a href="@Url.Action("Create", "Carro")" class="btn btn-secondary">Adicionar Carro</a>
            </p>
            <table class="table table-striped table-hover">
                <thead class="thead-dark">
                    <tr>
                        <th>@Html.DisplayNameFor(model => model.Nome)</th>
                        <th>@Html.DisplayNameFor(model => model.Descricao)</th>
                        <th>Ações</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@Html.DisplayFor(modelItem => item.Nome)</td>
                            <td>@Html.DisplayFor(modelItem => item.Descricao)</td>
                            <td>
                                <a href="@Url.Action("Edit", new { id = item.Id })" class="btn btn-info">Editar</a>
                                <a href="@Url.Action("Details", new { id = item.Id })" class="btn btn-primary">Detalhes</a>
                                <a href="@Url.Action("Delete", new { id = item.Id })" class="btn btn-danger">Excluir</a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>