CarGallery/Controllers/FabricanteController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using CarGallery;
using CarGallery.Models;
using Microsoft.AspNetCore.Authorization;

namespace CarGallery.Controllers
{
    [Authorize]
    public class FabricanteController : Controller
    {
        private readonly CarGalleryContext _context;

        public FabricanteController(CarGalleryContext context)
        {
            _context = context;
        }

        // GET: Fabricante
        public async Task<IActionResult> Index()
        {
            return View(await _context.Fabricantes.ToListAsync());
        }

        // GET: Fabricante/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var fabricante = await _context.Fabricantes
                .FirstOrDefaultAsync(m => m.Id == id);
            if (fabricante == null)
            {
                return NotFound();
            }

            return View(fabricante);
        }

        // GET: Fabricante/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Fabricante/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nome,Descricao")] Fabricante fabricante)
        {
            if (ModelState.IsValid)
            {
                _context.Add(fabricante);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(fabricante);
        }

        // GET: Fabricante/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var fabricante = await _context.Fabricantes.FindAsync(id);
            if (fabricante == null)
            {
                return NotFound();
            }
            return View(fabricante);
        }

        // POST: Fabricante/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nome,Descricao")] Fabricante fabricante)
        {
            if (id != fabricante.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(fabricante);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FabricanteExists(fabricante.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(fabricante);
        }

        // GET: Fabricante/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var fabricante = await _context.Fabricantes
                .FirstOrDefaultAsync(m => m.Id == id);
            if (fabricante == null)
            {
                return NotFound();
            }

            return View(fabricante);
        }

        // POST: Fabricante/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var fabricante = await _context.Fabricantes.FindAsync(id);
            if (fabricante != null)
            {
                // Exclui todos os carros associados ao fabricante
                var carros = await _context.Carros
                    .Where(c => c.FabricanteId == id)
                    .ToListAsync();
                _context.Carros.RemoveRange(carros);

                _context.Fabricantes.Remove(fabricante);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool FabricanteExists(int id)
        {
            return _context.Fabricantes.Any(e => e.Id == id);
        }
    }
}

CarGallery/Views/Shared/_CardCarro.cshtml
<style>
    body {
        background-color: #f8f9fa;
    }

    .container {
        padding-top: 20px;
    }

    .card {
        margin-bottom: 20px;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        position: relative;
        height: 420px;
        color: white;
        text-decoration: none;
        border: 2px solid transparent;
        overflow: hidden; /* Adiciona um overflow para o card para aplicar o efeito de desfoque somente na parte inferior */
    }

        .card:hover {
            border-color: #007bff;
        }

    .card-img-top {
        position: absolute;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        object-fit: cover;
    }

    .card-body {
        padding: 1.25rem;
        position: relative;
        display: flex;
        flex-direction: column;
        justify-content: flex-end;
        align-items: flex-end;
    }

    .card-title {
        font-size: 5rem;
        font-weight: 700;
        margin-bottom: 0.5rem;
        position: relative;
        z-index: 1; /* Certifica-se de que o texto está na frente do efeito de desfoque */
    }

    .card-text {
        color: white;
        font-size: 1.25rem;
        font-weight: 600;
        position: relative;
        z-index: 1; /* Certifica-se de que o texto está na frente do efeito de desfoque */
    }

    .card-body::after {
        content: ""; /* Cria um pseudo-elemento para aplicar o efeito de desfoque */
        position: absolute;
        bottom: 0;
        right: 0;
        width: 60%;
        border-radius: 10px 0 0 0; /* Ajuste conforme necessário */
        height: 40%; /* Altura do desfoque, ajuste conforme necessário */
        background: rgba(0, 0, 0, 0.2); /* Cor e opacidade do desfoque */
        backdrop-filter: blur(10px); /* Aplica o efeito de desfoque */
        z-index: 0; /* Garante que o efeito de desfoque esteja atrás do texto */
    }

    .btn-primary {
        background-color: #007bff;
        border-color: #007bff;
    }

        .btn-primary:hover {
            background-color: #0056b3;
            border-color: #0056b3;
        }
</style>

<div class="container text-center">
    <div class="row">
        @foreach (Carro item in ViewBag.Carros)
        {
            <div class="col">
                <a href="/Carro/Detail/@item.Id" class="card">
                    <img src="@item.Imagem" class="card-img-top" alt="Imagem do carro">
                    <div class="card-body">
                        <h5 class="card-title">@item.Nome</h5>
                        <p class="card-text">@item.DescricaoCurta</p>
                    </div>
                </a>
            </div>
        }
    </div>
</div>

CarGallery/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CarGallery</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CarGallery.styles.css" asp-append-version="true" />

    <style>
        body {
            background-color: #f8f9fa; /* Cor de fundo do corpo */
            color: #343a40; /* Cor do texto */
        }

        header {
            background-color: #ffffff; /* Cor de fundo do cabeçalho */
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1); /* Sombra */
        }

        .navbar-brand {
            color: #343a40 !important; /* Cor do texto do link da marca */
            font-weight: bold; /* Negrito */
        }

        .navbar-toggler {
            border-color: #343a40; /* Cor da borda do botão de alternância */
        }

        .navbar-text {
            color: #6c757d; /* Cor do texto da barra de navegação */
        }

        .nav-link {
            color: #343a40 !important; /* Cor do texto dos links da barra de navegação */
        }

            .nav-link:hover {
                color: #007bff !important; /* Cor do texto dos links da barra de navegação ao passar o mouse */
            }

        .footer {
            background-color: #ffffff; /* Cor de fundo do rodapé */
            color: #6c757d; /* Cor do texto do rodapé */
            padding: 20px 0; /* Preenchimento */
        }
    </style>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Search">Galeria de Carros</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                @if (User.Identity.IsAuthenticated)
                {
                    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                        <ul class="navbar-nav flex-grow-1">
                            @{
                                await Html.RenderPartialAsync("_MenuPesquisa");
                            }
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Fabricante" asp-action="Index">Fabricante</a>
                            </li>
                        </ul>
                        <span class="navbar-text">
                            Seja bem vindo, @User.Identity.Name
                        </span>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <form method="post" asp-controller="Account" asp-action="Logout">
                                <button type="submit" class="btn btn-danger">Deslogar</button>
                            </form>
                        }
                    </div>
                }
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            Feito por Lucas de Souza Ferreira nas aulas de Dot.Net
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

CarGallery/Views/Shared/_MenuPesquisa.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@inject CarGalleryContext context


<li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
        Carros
    </a>
    <ul class="dropdown-menu">
        <li><a class="dropdown-item" href="/Home/Search">Todos</a></li>
        <li><hr class="dropdown-divider"></li>
        @foreach (var fabricante in context.Fabricantes.ToList())
        {
            <li><a class="dropdown-item" href="/Home/Search?id=@fabricante.Id">@fabricante.Nome</a></li>
        }
    </ul>
</li>